In [1]:
import pandas as pd
import datetime as dt
import os

In [18]:
# Tabelle mit relevanten Wetterstationen erstellen
dict_wetter_stationen = {
    'ORT': ['Berlin','Berlin','Tokyo','Tokyo','Tokyo','London','New York','New York','Chicago'],    
    'STATION': ['10382099999','10385099999','47671099999','47662099999','47687099999','03768399999','72505394728','72502014734','72534014819']
}
df_wetter_stationen = pd.DataFrame(dict_wetter_stationen)
df_wetter_stationen.head()

      ORT      STATION
0  Berlin  10382099999
1  Berlin  10385099999
2   Tokyo  47671099999
3   Tokyo  47662099999
4   Tokyo  47687099999

In [3]:
# Gemeinsames Dataframe f√ºr alle eingelesenen Daten aus der CSV erzeugen. (nur relevante Spalten)
df_wetter_daten_csv = pd.DataFrame(pd.DataFrame(
    columns=[
       'STATION','DATE','SOURCE','LATITUDE','LONGITUDE','ELEVATION','NAME','REPORT_TYPE','QUALITY_CONTROL','WND','CIG','VIS','TMP','DEW','SLP' 
    ])
    ,dtype=str)

In [5]:
# Pfad zu den Wetterdaten
path_to_wetter_files = '/home/paul/python_projects/masterthesis/data/'
wetter_file_names = os.listdir(path_to_wetter_files)

In [12]:
# Wetterdaten (CSV-Dateien) in Dataframe einlesen. (nur relevante Spalten)
for csvfile in wetter_file_names:
    wetter_file_path = path_to_wetter_files + csvfile
    print(wetter_file_path)
    df_wetter_daten_csv_temp = pd.read_csv(wetter_file_path,header=0, sep=',', decimal=',', quotechar='"',dtype=str
        ,usecols=['STATION','DATE','SOURCE','LATITUDE','LONGITUDE','ELEVATION','NAME','REPORT_TYPE','QUALITY_CONTROL','WND','CIG','VIS','TMP','DEW','SLP' ]
    )
    df_wetter_daten_csv = df_wetter_daten_csv.append(df_wetter_daten_csv_temp)

df_wetter_daten_csv.head()

/home/paul/python_projects/masterthesis/data/10385099999_2015.csv
/home/paul/python_projects/masterthesis/data/72505394728_2017.csv
/home/paul/python_projects/masterthesis/data/03768399999_2019.csv
/home/paul/python_projects/masterthesis/data/10382099999_2017.csv
/home/paul/python_projects/masterthesis/data/72534014819_2016.csv
/home/paul/python_projects/masterthesis/data/47687099999_2019.csv
/home/paul/python_projects/masterthesis/data/72505394728_2007.csv
/home/paul/python_projects/masterthesis/data/72502014734_2014.csv
/home/paul/python_projects/masterthesis/data/03768399999_2008.csv
/home/paul/python_projects/masterthesis/data/10385099999_2007.csv
/home/paul/python_projects/masterthesis/data/72502014734_2008.csv
/home/paul/python_projects/masterthesis/data/47662099999_2008.csv
/home/paul/python_projects/masterthesis/data/47671099999_2018.csv
/home/paul/python_projects/masterthesis/data/47671099999_2014.csv
/home/paul/python_projects/masterthesis/data/03768399999_2017.csv
/home/paul/python_projects/masterthesis/data/10382099999_2009.csv
/home/paul/python_projects/masterthesis/data/72534014819_2017.csv
/home/paul/python_projects/masterthesis/data/03768399999_2013.csv
/home/paul/python_projects/masterthesis/data/10385099999_2014.csv
/home/paul/python_projects/masterthesis/data/72534014819_2018.csv
/home/paul/python_projects/masterthesis/data/03768399999_2007.csv
/home/paul/python_projects/masterthesis/data/10382099999_2007.csv
/home/paul/python_projects/masterthesis/data/47662099999_2018.csv
/home/paul/python_projects/masterthesis/data/47662099999_2014.csv
/home/paul/python_projects/masterthesis/data/47687099999_2013.csv
/home/paul/python_projects/masterthesis/data/47671099999_2011.csv
/home/paul/python_projects/masterthesis/data/03768399999_2018.csv
/home/paul/python_projects/masterthesis/data/47662099999_2016.csv
/home/paul/python_projects/masterthesis/data/72534014819_2019.csv
/home/paul/python_projects/masterthesis/data/47662099999_2012.csv
/home/paul/python_projects/masterthesis/data/47662099999_2007.csv
/home/paul/python_projects/masterthesis/data/47671099999_2008.csv
/home/paul/python_projects/masterthesis/data/47671099999_2013.csv
/home/paul/python_projects/masterthesis/data/72502014734_2015.csv
/home/paul/python_projects/masterthesis/data/47687099999_2017.csv
/home/paul/python_projects/masterthesis/data/72534014819_2011.csv
/home/paul/python_projects/masterthesis/data/72505394728_2009.csv
/home/paul/python_projects/masterthesis/data/10382099999_2012.csv
/home/paul/python_projects/masterthesis/data/47687099999_2011.csv
/home/paul/python_projects/masterthesis/data/47687099999_2010.csv
/home/paul/python_projects/masterthesis/data/10385099999_2010.csv
/home/paul/python_projects/masterthesis/data/47662099999_2019.csv
/home/paul/python_projects/masterthesis/data/72502014734_2018.csv
/home/paul/python_projects/masterthesis/data/10385099999_2011.csv
/home/paul/python_projects/masterthesis/data/72505394728_2010.csv
/home/paul/python_projects/masterthesis/data/10382099999_2015.csv
/home/paul/python_projects/masterthesis/data/72502014734_2012.csv
/home/paul/python_projects/masterthesis/data/47687099999_2016.csv
/home/paul/python_projects/masterthesis/data/03768399999_2012.csv
/home/paul/python_projects/masterthesis/data/10382099999_2013.csv
/home/paul/python_projects/masterthesis/data/10382099999_2011.csv
/home/paul/python_projects/masterthesis/data/47671099999_2015.csv
/home/paul/python_projects/masterthesis/data/47671099999_2007.csv
/home/paul/python_projects/masterthesis/data/72534014819_2008.csv
/home/paul/python_projects/masterthesis/data/72505394728_2016.csv
/home/paul/python_projects/masterthesis/data/03768399999_2015.csv
/home/paul/python_projects/masterthesis/data/10385099999_2013.csv
/home/paul/python_projects/masterthesis/data/47671099999_2019.csv
/home/paul/python_projects/masterthesis/data/47671099999_2010.csv
/home/paul/python_projects/masterthesis/data/72534014819_2007.csv
/home/paul/python_projects/masterthesis/data/72502014734_2019.csv
/home/paul/python_projects/masterthesis/data/72534014819_2010.csv
/home/paul/python_projects/masterthesis/data/47687099999_2007.csv
/home/paul/python_projects/masterthesis/data/72502014734_2013.csv
/home/paul/python_projects/masterthesis/data/72502014734_2017.csv
/home/paul/python_projects/masterthesis/data/72505394728_2013.csv
/home/paul/python_projects/masterthesis/data/47662099999_2013.csv
/home/paul/python_projects/masterthesis/data/10382099999_2008.csv
/home/paul/python_projects/masterthesis/data/47671099999_2016.csv
/home/paul/python_projects/masterthesis/data/47687099999_2018.csv
/home/paul/python_projects/masterthesis/data/47687099999_2008.csv
/home/paul/python_projects/masterthesis/data/47671099999_2017.csv
/home/paul/python_projects/masterthesis/data/47687099999_2014.csv
/home/paul/python_projects/masterthesis/data/10382099999_2016.csv
/home/paul/python_projects/masterthesis/data/72502014734_2009.csv
/home/paul/python_projects/masterthesis/data/47662099999_2009.csv
/home/paul/python_projects/masterthesis/data/72534014819_2009.csv
/home/paul/python_projects/masterthesis/data/10382099999_2014.csv
/home/paul/python_projects/masterthesis/data/72534014819_2012.csv
/home/paul/python_projects/masterthesis/data/72534014819_2014.csv
/home/paul/python_projects/masterthesis/data/47671099999_2012.csv
/home/paul/python_projects/masterthesis/data/72502014734_2010.csv
/home/paul/python_projects/masterthesis/data/72505394728_2008.csv
/home/paul/python_projects/masterthesis/data/47662099999_2010.csv
/home/paul/python_projects/masterthesis/data/72505394728_2015.csv
/home/paul/python_projects/masterthesis/data/72505394728_2012.csv
/home/paul/python_projects/masterthesis/data/72505394728_2019.csv
/home/paul/python_projects/masterthesis/data/10385099999_2012.csv
/home/paul/python_projects/masterthesis/data/47662099999_2015.csv
/home/paul/python_projects/masterthesis/data/10382099999_2010.csv
/home/paul/python_projects/masterthesis/data/10385099999_2009.csv
/home/paul/python_projects/masterthesis/data/72505394728_2011.csv
/home/paul/python_projects/masterthesis/data/72534014819_2015.csv
/home/paul/python_projects/masterthesis/data/03768399999_2010.csv
/home/paul/python_projects/masterthesis/data/03768399999_2014.csv
/home/paul/python_projects/masterthesis/data/72534014819_2013.csv
/home/paul/python_projects/masterthesis/data/03768399999_2009.csv
/home/paul/python_projects/masterthesis/data/47662099999_2017.csv
/home/paul/python_projects/masterthesis/data/10382099999_2019.csv
/home/paul/python_projects/masterthesis/data/10385099999_2018.csv
/home/paul/python_projects/masterthesis/data/47687099999_2012.csv
/home/paul/python_projects/masterthesis/data/10385099999_2017.csv
/home/paul/python_projects/masterthesis/data/47687099999_2015.csv
/home/paul/python_projects/masterthesis/data/72502014734_2011.csv
/home/paul/python_projects/masterthesis/data/47662099999_2011.csv
/home/paul/python_projects/masterthesis/data/03768399999_2011.csv
/home/paul/python_projects/masterthesis/data/72502014734_2016.csv
/home/paul/python_projects/masterthesis/data/10382099999_2018.csv
/home/paul/python_projects/masterthesis/data/10385099999_2016.csv
/home/paul/python_projects/masterthesis/data/72505394728_2018.csv
/home/paul/python_projects/masterthesis/data/47687099999_2009.csv
/home/paul/python_projects/masterthesis/data/03768399999_2016.csv
/home/paul/python_projects/masterthesis/data/10385099999_2019.csv
/home/paul/python_projects/masterthesis/data/72505394728_2014.csv
/home/paul/python_projects/masterthesis/data/72502014734_2007.csv
/home/paul/python_projects/masterthesis/data/47671099999_2009.csv
/home/paul/python_projects/masterthesis/data/10385099999_2008.csv

,STATION,DATE,SOURCE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,QUALITY_CONTROL,WND,CIG,VIS,TMP,DEW,SLP
0,10385099999,2015-01-01T00:20:00,4,52.380001,13.5225,47.85,"SCHONEFELD, GM",FM-15,V020,"270,1,N,0051,1","00183,1,9,N","001400,1,9,9","+0040,1","+0040,1","99999,9"
1,10385099999,2015-01-01T00:50:00,4,52.380001,13.5225,47.85,"SCHONEFELD, GM",FM-15,V020,"260,1,N,0051,1","00213,1,9,N","001500,1,9,9","+0040,1","+0040,1","99999,9"
2,10385099999,2015-01-01T01:20:00,4,52.380001,13.5225,47.85,"SCHONEFELD, GM",FM-15,V020,"270,1,N,0046,1","00213,1,9,N","002600,1,9,9","+0050,1","+0050,1","99999,9"
3,10385099999,2015-01-01T01:50:00,4,52.380001,13.5225,47.85,"SCHONEFELD, GM",FM-15,V020,"270,1,N,0051,1","00244,1,9,N","003500,1,9,9","+0040,1","+0040,1","99999,9"
4,10385099999,2015-01-01T02:20:00,4,52.380001,13.5225,47.85,"SCHONEFELD, GM",FM-15,V020,"280,1,N,0051,1","00274,1,9,N","003500,1,9,9","+0040,1","+0040,1","99999,9"

In [17]:
# Ort zu den Stationen Joinen
df_wetter_daten_raw = pd.merge(left=df_wetter_stationen, right=df_wetter_daten_csv, on="STATION")
df_wetter_daten_raw.head()

array(['99999,9', '10138,5', '10129,5', ..., '09791,1', '09802,5',
       '09875,6'], dtype=object)